### ISSUE TITLE
EU part 2报错

### ISSUE THREAD

**Issue by yihjian** [Vincent-Cui/flights_checker#3]
```
NameError: name 'df' is not defined
Traceback:

File "/usr/local/lib/python3.6/site-packages/streamlit/ScriptRunner.py", line 319, in _run_script
    exec(code, module.__dict__)
File "/var/www/app/flights.py", line 461, in <module>
    st.write(df, unsafe_allow_html=True)
```
盲猜是df1打成了df

**Comment by Vincent-Cui** [comment]
感谢！确实是typo了，已经更正！请再试一下 ---Wencong CuiPh.D. Student, Graduate Research & Teaching AssistantDepartment of Geography, Texas A&M University From: Yihong JianSent: 2020年7月19日 11:55To: Vincent-Cui/flights_checkerCc: SubscribedSubject: [Vincent-Cui/flights_checker] EU part 2报错 (#3) NameError: name 'df' is not definedTraceback: File "/usr/local/lib/python3.6/site-packages/streamlit/ScriptRunner.py", line 319, in _run_script    exec(code, module.__dict__)File "/var/www/app/flights.py", line 461, in <module>    st.write(df, unsafe_allow_html=True)盲猜是df1打成了df—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Vincent-Cui** [comment]
是因为漏打了一行，已经更正
